services:
  mosquitto:
    image: eclipse-mosquitto:latest
    networks:
      - iot
    ports:
      - "1883:1883"
    env_file:
      - .env
  db:
    image: postgres
    networks:
      - iot
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
  influxdb:
    image: influxdb
    networks:
      - iot
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    ports:
      - "8086:8086"
    env_file:
    - .env
  fastapi:
    image: my-api-img
    networks:
      - iot
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - influxdb
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}"
      INFLUXDB_URL: "http://influxdb:8086"
networks:
  iot: